const demoGroups={"ИС-21":["Иванов Артем","Петрова Мария","Саидов Камиль"],"ИС-22":["Смирнов Даниил","Кузнецова Алиса","Морозов Кирилл"],"ПИ-31":["Волков Максим","Егорова Софья","Беляев Никита"]};
const demoTickets=[1,2,3,4,5].map(n=>({number:n,questions:[`Теоретический вопрос билета ${n}.`,`Практическое задание билета ${n}.`,`Обоснование решения для билета ${n}.`]}));
let groups={},tickets=[],log=JSON.parse(localStorage.getItem("ticket-results")||"[]"),resultsHandle=null;
const $=s=>document.querySelector(s),groupSelect=$("#groupSelect"),studentSelect=$("#studentSelect"),generateButton=$("#generateTicket"),randomButton=$("#randomStudent"),dialog=$("#resultDialog");
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
const splitName=fullName=>{const [lastName="",...rest]=fullName.trim().split(/\s+/);return{lastName,firstName:rest.join(" "),fullName}};
function status(text,error=false){$("#dataStatus").textContent=text;$("#dataStatus").classList.toggle("error",error)}
function stats(){$("#statGroups").textContent=Object.keys(groups).length;$("#statStudents").textContent=Object.values(groups).reduce((n,a)=>n+a.length,0);$("#statTickets").textContent=tickets.length}
function updateButton(){generateButton.disabled=!(groupSelect.value&&studentSelect.value&&tickets.length)}
function renderGroups(){const names=Object.keys(groups);groupSelect.innerHTML='<option value="">Выберите группу</option>'+names.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");groupSelect.disabled=!names.length;renderStudents();stats()}
function renderStudents(){const list=groups[groupSelect.value]||[];studentSelect.innerHTML=`<option value="">${groupSelect.value?(list.length?"Выберите студента":"В этой группе нет студентов"):"Сначала выберите группу"}</option>`+list.map(x=>`<option value="${esc(x.fullName)}">${esc(x.fullName)}</option>`).join("");studentSelect.disabled=!list.length;randomButton.disabled=!list.length;updateButton()}
function renderLog(){$("#logBody").innerHTML=log.map(r=>`<tr><td>${esc(r.group)}</td><td>${esc(r.lastName)}</td><td>${esc(r.firstName)}</td><td>${r.ticket}</td><td>${esc(r.date)}</td><td><span class="repeat repeat-${r.repeat==="да"?"yes":"no"}">${r.repeat}</span></td></tr>`).join("")}
function drawTicket(t,s){$("#ticketNumber").textContent=`Билет ${t.number}`;$("#ticketStudent").textContent=s;$("#questions").innerHTML=t.questions.map(q=>`<li>${esc(q)}</li>`).join("")}
function parseTickets(text){return text.split(/(?=Билет\s+\d+)/gi).map(b=>{b=b.trim();const number=b.match(/^Билет\s+(\d+)/i)?.[1];const questions=b.split(/\r?\n/).map(x=>x.trim()).filter(x=>/^\d+\.\s+/.test(x)).map(x=>x.replace(/^\d+\.\s+/,""));return number&&questions.length>=3?{number:Number(number),questions:questions.slice(0,3)}:null}).filter(Boolean)}
function workbookBlob(){const rows=log.map(r=>({"Группа":r.group,"Фамилия":r.lastName,"Имя":r.firstName,"Номер билета":r.ticket,"Дата и время":r.date,"Повтор (да/нет)":r.repeat})),ws=XLSX.utils.json_to_sheet(rows,{header:["Группа","Фамилия","Имя","Номер билета","Дата и время","Повтор (да/нет)"]}),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,"Результаты");return new Blob([XLSX.write(wb,{bookType:"xlsx",type:"array"})],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})}
function download(){const a=document.createElement("a");a.href=URL.createObjectURL(workbookBlob());a.download="results.xlsx";a.click();URL.revokeObjectURL(a.href)}
async function saveNow(){localStorage.setItem("ticket-results",JSON.stringify(log));if(!resultsHandle)return status("Результат сохранён в браузере. Подключите results.xlsx для записи в файл");try{const w=await resultsHandle.createWritable();await w.write(workbookBlob());await w.close();status("results.xlsx сохранён сразу после генерации")}catch{status("Файл недоступен. Закройте results.xlsx в Excel и подключите повторно",true)}}
groupSelect.addEventListener("change",renderStudents);studentSelect.addEventListener("change",updateButton);randomButton.addEventListener("click",()=>{const a=groups[groupSelect.value]||[];if(a.length){studentSelect.value=a[Math.floor(Math.random()*a.length)].fullName;updateButton()}});
generateButton.addEventListener("click",()=>{const student=(groups[groupSelect.value]||[]).find(x=>x.fullName===studentSelect.value),first=log.find(r=>r.group===groupSelect.value&&r.lastName===student.lastName&&r.firstName===student.firstName),ticket=first?tickets.find(t=>t.number===Number(first.ticket)):tickets[Math.floor(Math.random()*tickets.length)];if(!ticket)return status("Ранее назначенный билет отсутствует в текущем tickets.docx",true);const row={group:groupSelect.value,lastName:student.lastName,firstName:student.firstName,ticket:ticket.number,date:new Date().toLocaleString("ru-RU"),repeat:first?"да":"нет"};log.push(row);renderLog();drawTicket(ticket,student.fullName);saveNow();$("#dialogNumber").textContent=ticket.number;$("#dialogStudent").textContent=`${row.group} · ${student.fullName}${first?" · повторная выдача":""}`;$("#dialogQuestions").innerHTML=ticket.questions.map(q=>`<li>${esc(q)}</li>`).join("");dialog.showModal()});
$("#studentsFile").addEventListener("change",async e=>{try{const f=e.target.files[0];if(!f)return;const wb=XLSX.read(await f.arrayBuffer());groups={};wb.SheetNames.forEach(n=>{groups[n]=XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1}).slice(1).map(r=>({lastName:String(r[0]||"").trim(),firstName:String(r[1]||"").trim()})).filter(x=>x.lastName||x.firstName).map(x=>({...x,fullName:`${x.lastName} ${x.firstName}`.trim()}))});renderGroups();status(`Загружено групп: ${wb.SheetNames.length}`)}catch{status("Не удалось прочитать students.xlsx. Проверьте формат файла",true)}});
$("#ticketsFile").addEventListener("change",async e=>{try{const f=e.target.files[0];if(!f)return;const text=f.name.toLowerCase().endsWith(".docx")?(await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()})).value:await f.text();tickets=parseTickets(text);stats();updateButton();status(tickets.length?`Загружено корректных билетов: ${tickets.length}`:"Корректных билетов с тремя вопросами не найдено",!tickets.length)}catch{status("Не удалось прочитать tickets.docx",true)}});
$("#loadDemo").addEventListener("click",()=>{groups=structuredClone(demoGroups);Object.keys(groups).forEach(g=>groups[g]=groups[g].map(splitName));tickets=structuredClone(demoTickets);renderGroups();status("Демонстрационные данные готовы")});
$("#resultsFile").addEventListener("click",async()=>{if(!window.showSaveFilePicker)return download();try{resultsHandle=await showSaveFilePicker({suggestedName:"results.xlsx",types:[{description:"Excel",accept:{"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":[".xlsx"]}}]});await saveNow()}catch(e){if(e.name!=="AbortError")status("Не удалось подключить results.xlsx",true)}});
$("#exportXlsx").addEventListener("click",download);$("#closeDialog").addEventListener("click",()=>dialog.close());$("#dialogDone").addEventListener("click",()=>dialog.close());renderGroups();renderLog();
